name: Deploy VitePress to GitHub Pages

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build VitePress site
        run: npm run build # Adjust if your build script is different
